#!/usr/bin/env python
import sys
import getopt
from ARFF import ARFF

def main(argv):
	help = """Usage: %s [OPTIONS] [INPUT [OUTPUT]]
Convert ARFF file to PARF readable file

Options:
    --help		display this help and exit
	""" % argv[0].split('/')[-1]

	try:
		opts, args = getopt.getopt(argv[1:], "h",
			["help"])
	except getopt.error, msg:
		print msg
		return 0

	# Parse arguments
	for opt, arg in opts:
		if opt in ('-h','--help'):
			print help
			return 0

	if len(args) > 0:
		input = open(args.pop(0),'r')
	else:
		input = sys.stdin

	if len(args) > 0:
		input = open(args.pop(0),'w')
	else:
		output = sys.stdout

	# Go do real work
	a = ARFF()
	a.parseARFF(input)
	a.writePARF(output)

	input.close()
	output.close()

if __name__ == '__main__':
	sys.exit(main(sys.argv))
